application: compress-css
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /style\.css
  static_files: static/style.css
  upload: static/style\.css

- url: /submit\.js
  static_files: static/submit.js
  upload: static/submit\.js

- url: /(.*\.png)
  static_files: static/\1
  upload: static/(.*\.png)

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"